// const questionSeed = [
//     {
//       id: 1,
//       questionStr: 'Stofzuiger werkt niet meer/ reageert niet meer?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 2,
//       questionStr: 'Stofzuiger stinkt?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 3,
//       questionStr: 'Snoer rolt niet op?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 4,
//       questionStr: 'Stofzuiger laadt niet meer op?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 5,
//       questionStr: 'Stofzuiger is uitgevallen?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 6,
//       questionStr: 'Stofzuiger zuigt niet goed?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 7,
//       questionStr: 'Wieltjes draaien niet meer?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 8,
//       questionStr: 'Er is geen verbinding met de app?',
//       parentQuestionId: null,
//       issueId: null,
//       deviceTypeId: 1,
//     },
//     {
//       id: 9,
//       questionStr: 'Zit de stekker goed in het stopcontact?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 10,
//       questionStr: 'Is de batterij opgeladen?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 11,
//       questionStr: 'Zitten stofzak/ stofbak/filters goed in de stofzuiger?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 12,
//       questionStr: 'Zit klepje op de buis van de stofzuiger goed /is hij op de juiste manier gesloten?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 13,
//       questionStr: 'Is het snoer nog intact/ geen brandvlekken of beschadigd?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 14,
//       questionStr: 'Werkt het stopcontact wel?',
//       parentQuestionId: 1,
//       issueId: 1,
//       deviceTypeId: 1,
//     },
//     {
//       id: 15,
//       questionStr: 'Probleem ligt niet bij snoer of stopcontact?',
//       parentQuestionId: 1,
//       issueId: 2,
//       deviceTypeId: 1,
//     },
//     {
//       id: 16,
//       questionStr: 'Werkt niet of laadt niet goed op?',
//       parentQuestionId: 1,
//       issueId: 3,
//       deviceTypeId: 1,
//     },
//     {
//       id: 17,
//       questionStr: 'Laadstation aangesloten aan werkend stopcontact?',
//       parentQuestionId: 1,
//       issueId: 4,
//       deviceTypeId: 1,
//     },
//     {
//       id: 18,
//       questionStr: 'Helpen de oplossingen hierboven niet?',
//       parentQuestionId: 1,
//       issueId: 5,
//       deviceTypeId: 1,
//     },
//     {
//       id: 19,
//       questionStr: 'Zit er iets vast in de voet, zuigbuis of slang?',
//       parentQuestionId: 2,
//       issueId: 6,
//       deviceTypeId: 1,
//     },
//     {
//       id: 20,
//       questionStr: 'Is de stofzuigerzak of het reservoir geleegd?',
//       parentQuestionId: 2,
//       issueId: 6,
//       deviceTypeId: 1,
//     },{
//         id: 21,
//         questionStr: 'Zijn de filters schoongemaakt of vervangen?',
//         parentQuestionId: 2,
//         issueId: 6,
//         deviceTypeId: 1,
//       },
//       {
//         id: 22,
//         questionStr: 'Merk je een verbrande lucht op?',
//         parentQuestionId: 2,
//         issueId: 7,
//         deviceTypeId: 1,
//       },
//       {
//         id: 23,
//         questionStr: 'Rolt het snoer niet meer goed op?',
//         parentQuestionId: 3,
//         issueId: 8,
//         deviceTypeId: 1,
//       },
//       {
//         id: 24,
//         questionStr: 'Draait het oprolmechanisme niet goed?',
//         parentQuestionId: 3,
//         issueId: 9,
//         deviceTypeId: 1,
//       },
//       {
//         id: 25,
//         questionStr: 'Werkt het toestel met een nieuwe batterij?',
//         parentQuestionId: 4,
//         issueId: 10,
//         deviceTypeId: 1,
//       },
//       {
//         id: 26,
//         questionStr: 'Is het laadstation aangesloten op een werkend stopcontact?',
//         parentQuestionId: 11,
//         issueId: null,
//         deviceTypeId: 1,
//       },
//       {
//         id: 27,
//         questionStr: 'Kan je een andere batterij opladen aan dit laadstation?',
//         parentQuestionId: 11,
//         issueId: null,
//         deviceTypeId: 1,
//       },
//       {
//         id: 28,
//         questionStr: 'Zit er een voorwerp vast?',
//         parentQuestionId: 5,
//         issueId: 12,
//         deviceTypeId: 1,
//       },
//       {
//         id: 29,
//         questionStr: 'Zie je niets dat vastzit? Vervang de zak of ledig het reservoir?',
//         parentQuestionId: 5,
//         issueId: 12,
//         deviceTypeId: 1,
//       },
//       {
//         id: 30,
//         questionStr: 'Helpt niets van hierboven? Maak de filters schoon of vervang ze?',
//         parentQuestionId: 5,
//         issueId: 12,
//         deviceTypeId: 1,
//       },
//       {
//         id: 31,
//         questionStr: 'Merk je een verbrande lucht op?',
//         parentQuestionId: 5,
//         issueId: 13,
//         deviceTypeId: 1,
//       },
//       {
//         id: 32,
//         questionStr: 'Niets doorgebrand bij stopcontact, stekker, snoer?',
//         parentQuestionId: 5,
//         issueId: 13,
//         deviceTypeId: 1,
//       },
//       {
//         id: 33,
//         questionStr: 'Is de zuigkrachtregeling veranderd?',
//         parentQuestionId: 6,
//         issueId: 14,
//         deviceTypeId: 1,
//       },
//       {
//         id: 34,
//         questionStr: 'Is er minder zuigkracht?',
//         parentQuestionId: 6,
//         issueId: 15,
//         deviceTypeId: 1,
//       },
//       {
//         id: 35,
//         questionStr: 'Voel je zuigkracht?',
//         parentQuestionId: 6,
//         issueId: 16,
//         deviceTypeId: 1,
//       },
//       {
//         id: 36,
//         questionStr: 'Voel je geen zuigkracht?',
//         parentQuestionId: 6,
//         issueId: 16,
//         deviceTypeId: 1,
//       },
//       {
//         id: 37,
//         questionStr: 'Zit er een lek in de plastic slang?',
//         parentQuestionId: 6,
//         issueId: 17,
//         deviceTypeId: 1,
//       },
//       {
//         id: 38,
//         questionStr: 'Zit er een rubberen afsluiting los of is er een afsluiting kapot?',
//         parentQuestionId: 6,
//         issueId: 17,
//         deviceTypeId: 1,
//       },
//       {
//         id: 39,
//         questionStr: 'Is de plastic slang kapot dicht bij een uiteinde?',
//         parentQuestionId: 6,
//         issueId: 18,
//         deviceTypeId: 1,
//       },
//       {
//         id: 40,
//         questionStr: 'Draaien de wieltjes niet meer goed?',
//         parentQuestionId: 7,
//         issueId: 19,
//         deviceTypeId: 1,
//       },{
//         id: 41,
//         questionStr: 'Draaien de wieltjes nog steeds niet goed na schoonmaken?',
//         parentQuestionId: 7,
//         issueId: 20,
//         deviceTypeId: 1,
//       },
//       {
//         id: 42,
//         questionStr: 'Heb je de juiste app gedownload?',
//         parentQuestionId: 8,
//         issueId: 21,
//         deviceTypeId: 1,
//       },
//       {
//         id: 43,
//         questionStr: 'Is er wifibereik tot aan het laadstation?',
//         parentQuestionId: 8,
//         issueId: 21,
//         deviceTypeId: 1,
//       },
//       {
//         id: 44,
//         questionStr: 'Zijn smartphone en robot op hetzelfde wifinetwerk én -frequentie aangesloten?',
//         parentQuestionId: 8,
//         issueId: 21,
//         deviceTypeId: 1,
//       },
//       {
//         id: 45,
//         questionStr: 'Heb je de stofzuiger al eens uitgeschakeld en na vijf minuten weer aangeschakeld?',
//         parentQuestionId: 8,
//         issueId: 21,
//         deviceTypeId: 1,
//       },
//       {
//         id: 46,
//         questionStr: 'Lukt het helemaal niet om een verbinding met de stofzuiger te maken?',
//         parentQuestionId: 8,
//         issueId: 22,
//         deviceTypeId: 1,
//       },
//   ];
  
//   export default questionSeed;
  

const questionSeed = [
  {
    questionStr: 'Stofzuiger werkt niet meer/ reageert niet meer?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Stofzuiger stinkt?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Snoer rolt niet op?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Stofzuiger laadt niet meer op?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Stofzuiger is uitgevallen?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Stofzuiger zuigt niet goed?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Wieltjes draaien niet meer?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Er is geen verbinding met de app?',
    parentQuestionId: null,
    issueId: null,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Zit de stekker goed in het stopcontact?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Is de batterij opgeladen?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Zitten stofzak/ stofbak/filters goed in de stofzuiger?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Zit klepje op de buis van de stofzuiger goed /is hij op de juiste manier gesloten?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Is het snoer nog intact/ geen brandvlekken of beschadigd?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Werkt het stopcontact wel?',
    parentQuestionId: 1,
    issueId: 1,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Probleem ligt niet bij snoer of stopcontact?',
    parentQuestionId: 1,
    issueId: 2,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Werkt niet of laadt niet goed op?',
    parentQuestionId: 1,
    issueId: 3,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Laadstation aangesloten aan werkend stopcontact?',
    parentQuestionId: 1,
    issueId: 4,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Helpen de oplossingen hierboven niet?',
    parentQuestionId: 1,
    issueId: 5,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Zit er iets vast in de voet, zuigbuis of slang?',
    parentQuestionId: 2,
    issueId: 6,
    deviceTypeId: 1,
  },
  {
    questionStr: 'Is de stofzuigerzak of het reservoir geleegd?',
    parentQuestionId: 2,
    issueId: 6,
    deviceTypeId: 1,
  },{
      questionStr: 'Zijn de filters schoongemaakt of vervangen?',
      parentQuestionId: 2,
      issueId: 6,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Merk je een verbrande lucht op?',
      parentQuestionId: 2,
      issueId: 7,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Rolt het snoer niet meer goed op?',
      parentQuestionId: 3,
      issueId: 8,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Draait het oprolmechanisme niet goed?',
      parentQuestionId: 3,
      issueId: 9,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Werkt het toestel met een nieuwe batterij?',
      parentQuestionId: 4,
      issueId: 10,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Is het laadstation aangesloten op een werkend stopcontact?',
      parentQuestionId: 11,
      issueId: null,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Kan je een andere batterij opladen aan dit laadstation?',
      parentQuestionId: 11,
      issueId: null,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Zit er een voorwerp vast?',
      parentQuestionId: 5,
      issueId: 12,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Zie je niets dat vastzit? Vervang de zak of ledig het reservoir?',
      parentQuestionId: 5,
      issueId: 12,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Helpt niets van hierboven? Maak de filters schoon of vervang ze?',
      parentQuestionId: 5,
      issueId: 12,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Merk je een verbrande lucht op?',
      parentQuestionId: 5,
      issueId: 13,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Niets doorgebrand bij stopcontact, stekker, snoer?',
      parentQuestionId: 5,
      issueId: 13,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Is de zuigkrachtregeling veranderd?',
      parentQuestionId: 6,
      issueId: 14,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Is er minder zuigkracht?',
      parentQuestionId: 6,
      issueId: 15,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Voel je zuigkracht?',
      parentQuestionId: 6,
      issueId: 16,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Voel je geen zuigkracht?',
      parentQuestionId: 6,
      issueId: 16,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Zit er een lek in de plastic slang?',
      parentQuestionId: 6,
      issueId: 17,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Zit er een rubberen afsluiting los of is er een afsluiting kapot?',
      parentQuestionId: 6,
      issueId: 17,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Is de plastic slang kapot dicht bij een uiteinde?',
      parentQuestionId: 6,
      issueId: 18,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Draaien de wieltjes niet meer goed?',
      parentQuestionId: 7,
      issueId: 19,
      deviceTypeId: 1,
    },{
      questionStr: 'Draaien de wieltjes nog steeds niet goed na schoonmaken?',
      parentQuestionId: 7,
      issueId: 20,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Heb je de juiste app gedownload?',
      parentQuestionId: 8,
      issueId: 21,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Is er wifibereik tot aan het laadstation?',
      parentQuestionId: 8,
      issueId: 21,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Zijn smartphone en robot op hetzelfde wifinetwerk én -frequentie aangesloten?',
      parentQuestionId: 8,
      issueId: 21,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Heb je de stofzuiger al eens uitgeschakeld en na vijf minuten weer aangeschakeld?',
      parentQuestionId: 8,
      issueId: 21,
      deviceTypeId: 1,
    },
    {
      questionStr: 'Lukt het helemaal niet om een verbinding met de stofzuiger te maken?',
      parentQuestionId: 8,
      issueId: 22,
      deviceTypeId: 1,
    },
];

export {questionSeed};
